### PR TITLE
Add the ability to instantiate Hyperbee without 'new'

### PR DESCRIPTION
**Pull request by pfrazee**
This PR makes it possible to instantiate Hyperbee with or without new.

This would keep Hyperbee and Hyperdrive matching each other's instantiation styles

See https://github.com/hypercore-protocol/website/issues/12

### CODE REVIEW

**Comment by mafintosh** [comment]
I'd rather move everything else to classes

**Comment by pfrazee** [comment]
That'd be pretty challenging, wouldn't it? A lot of code using hyperdrive would have to update

**Comment by mafintosh** [comment]
You can do the same approach as here can't you?

Alternatively I'd be okay moving this line to just exporting the class, https://github.com/hypercore-protocol/hyperdrive/blob/master/index.js#L34, and doing a major bump. Pretty simple upgrade path.

Would strongly prefer moving everything towards the new pattern instead of moving newer code towards the old pattern.

**Comment by mafintosh** [comment]
Corestore is a class as well

**Comment by pfrazee** [comment]
Corestore bothers me less because it's less of a mirror API. Hyperbee and Hyperdrive seem like they should match up.

I can understand why you wouldn't want the code in this PR, but this approach allows us to adopt the pain, whereas changing Hyperdrive pushes the pain onto our users.

If we don't want to change Hyperbee like this and want to migrate to `new Hyperdrive` then I'd suggest using this pattern in Hyperdrive and changing all our docs to use `new`. That way we could start the process of moving to the `new` pattern without breaking peoples' code.

**Comment by mafintosh** [comment]
Ya I just saw corestore used not as a class in the issue from you linked.
I'd do it like this to avoid "reverting" the HD code:

```
module.exports = function HyperdriveCompat (...args) {
  // rename constructor to initialise and call initiliase from the Hyperdrive constructor
  Hyperdrive.prototype.initialise.call(this, ...args)
}

Object.setPrototypeOf(HyperdriveCompat.prototype, Hyperdrive.prototype)
```

**Comment by pfrazee** [comment]
👍 Sounds good

**Pull request closed without merging**
